name: Generate Pacman Contribution Graph
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Kaptalcide
          outputs: |
            ./output/pacman-contribution-graph.svg?color_snake=yellow&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39&type=pacman
            ./output/pacman-contribution-graph-dark.svg?color_snake=yellow&color_dots=#161b22,#0d4429,#006d32,#26a641,#39d353&type=pacman

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: output
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
